--PRIMARY
USE [master]
GO
ALTER AVAILABILITY GROUP [GROUP1]
MODIFY REPLICA ON N'SERVER3' WITH (SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL))
GO
ALTER AVAILABILITY GROUP [GROUP2]
MODIFY REPLICA ON N'SERVER3' WITH (SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL))
GO


--Secondary
USE [master]
GO
ALTER AVAILABILITY GROUP [GROUP1]
MODIFY REPLICA ON N'SERVER3' WITH (SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL))
GO
ALTER AVAILABILITY GROUP [GROUP2]
MODIFY REPLICA ON N'SERVER3' WITH (SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL))
GO