BEGIN TRANSACTION;
--tsql

IF (@@ERROR <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:
GO



IF (@@ERROR <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:
GO


DECLARE
    	@ERROR_SEVERITY INT,
    	@ERROR_STATE	INT,
    	@ERROR_NUMBER	INT,
    	@ERROR_LINE		INT,
    	@ERROR_MESSAGE	NVARCHAR(4000);

    SELECT
    	@ERROR_SEVERITY = ERROR_SEVERITY(),
    	@ERROR_STATE	= ERROR_STATE(),
    	@ERROR_NUMBER	= ERROR_NUMBER(),
    	@ERROR_LINE		= ERROR_LINE(),
    	@ERROR_MESSAGE	= ERROR_MESSAGE();

    RAISERROR('Msg %d, Line %d, :%s',
    	ERROR_SEVERITY(),
    	ERROR_STATE(),
    	ERROR_NUMBER(),
    	ERROR_LINE(),
    	ERROR_MESSAGE());
