EXEC sp_resetstatus [ DB1];
ALTER DATABASE [ DB1] SET EMERGENCY;
DBCC checkdb([ DB1]);
ALTER DATABASE [ DB1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DBCC CheckDB ([ DB1], REPAIR_ALLOW_DATA_LOSS);
ALTER DATABASE [ DB1] SET MULTI_USER;
