alter database DB1_PROD set AUTO_UPDATE_STATISTICS_ASYNC OFF

alter database DB2_PROD set AUTO_UPDATE_STATISTICS_ASYNC OFF

select * from sys.databases

USE master;
GO
ALTER DATABASE DB1_PROD
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

ALTER DATABASE DB2_PROD
SET MULTI_USER;
GO